from fccgroup.patterns.library import fingerprints

FPPS_SET = {
    'Elements (loose)': "Elements",
    'Hydrocarbons': False,
    'PAH derivatives': False,
    'PAH derivatives hydrocarbon': "PAH derivatives",
    'Contains C-C': False,
    'Contains C=C': False,
    'Contains C#C': False,
    'Contains aliphatic C': False,
    'Contains aromatic C': False,
    'Aliphatic hydrocarbons': False,
    'Alkenes': "Alkenes",
    'Alkanes': "Alkanes",
    'Biphenyls/Terphenyls': "Biphenyls/Terphenyls",
    'Benzoates': "Benzoates",
    'Ortho-phthalates': "Ortho-phthalates",
    'Terephthalates': "Terephthalates",
    'Stearic acid esters': "Stearic acid esters",
    'Adipic acid esters': "Adipic acid esters",
    'Citric acid esters': "Citric acid esters",
    'Organo O (strict)': False,
    'Contains O': False,
    'Alkyl phenols': "Alkyl phenols",
    'Hindered phenol derivatives': "Hindered phenol derivatives",
    'Bisphenol M derivatives': False,
    'Bisphenol P derivatives': False,
    'Bisphenol bridge derivatives': False,
    'Bisphenol derivatives': "Bisphenol derivatives",
    'Benzophenone derivatives': "Benzophenone derivatives",
    'Acetophenone derivatives': "Acetophenone derivatives",
    'Contains peroxide': "Contains peroxide",
    'Tetramethylpiperidine derivatives': "Tetramethylpiperidine derivatives",
    "Benzotriazines (1,2,3) derivatives": False,
    "Benzotriazines (1,2,4) derivatives": False,
    'Benzotriazoles derivatives': "Benzotriazoles derivatives",
    "Triazines (1,2,3) derivatives": False,
    "Triazines (1,2,4) derivatives": False,
    "Triazines (1,3,5) derivatives": False,
    'Triazines derivatives': "Triazines derivatives",
    'Contains isocyanate': "Contains isocyanate",
    "Organo N (strict)": False,
    "Contains aromatic C": False,
    "Contains nitrile": False,
    "Contains N": False,
    'Contains nitrosamine': "Contains nitrosamine",
    'Contains nitrile': "Contains nitrile",
    'Contains nitro': "Contains nitro",
    'Primary aromatic amines': "Primary aromatic amines",
    'Secondary aromatic amines': "Secondary aromatic amines",
    'Tertiary aromatic amines': "Tertiary aromatic amines",
    'Organophosphates': "Organophosphates",
    'Organophosphites': "Organophosphites",
    'Contains S-heterocycle': "Contains S-heterocycle",
    'Contains dithiocarbamate': "Contains dithiocarbamate",
    'Contains isothiocyanate': "Contains isothiocyanate",
    'PFAS': "PFAS",
    'Organo Cl (strict)': False,
    'Contains C~Cl': False,
    'Chlorinated alkanes': "Chlorinated alkanes",
    "Contains C~Br": False,
    'PCBs': "PCBs",
    'PCDDs': "PCDDs",
    'PCDFs': "PCDFs",
    'PBDEs': "PBDEs",
    'Siloxanes': "Siloxanes",
    'Contains Organo Sn': "Contains Organo Sn"
    }

REDUCED_FPPS = {}
for fp_name, fp_value in fingerprints.items():
    if fp_name in FPPS_SET:
        REDUCED_FPPS[fp_name] = fingerprints[fp_name]